import Link from 'next/link';

export default function TermsOfService() {
  const styles = {
    main: { color: '#e2e8f0', fontFamily: 'sans-serif', maxWidth: '56rem', margin: '0 auto', padding: '3rem 1.5rem', minHeight: '100vh' },
    h1: { color: '#ffffff', fontSize: '1.875rem', fontWeight: '700', marginBottom: '0.75rem', borderBottom: '1px solid #334155', paddingBottom: '1rem' },
    date: { color: '#94a3b8', fontSize: '0.875rem', marginBottom: '2rem' },
    section: { display: 'flex', flexDirection: 'column', gap: '2rem' },
    h2: { color: '#34d399', fontSize: '1.25rem', fontWeight: '600', marginBottom: '0.75rem' },
    p: { color: '#cbd5e1', lineHeight: '1.625' },
    card: { backgroundColor: 'rgba(69, 26, 3, 0.3)', padding: '1.25rem', borderRadius: '0.75rem', border: '1px solid #78350f' },
    cardH2: { color: '#fbbf24', fontSize: '1.25rem', fontWeight: '600', marginBottom: '0.75rem' },
    footerLink: { color: '#34d399', textDecoration: 'none', display: 'inline-block', marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid #334155', width: '100%' }
  };

  return (
    <main style={styles.main}>
      <h1 style={styles.h1}>Terms of Service</h1>
      <p style={styles.date}>Last updated: May 29, 2026</p>
      
      <section style={styles.section}>
        <div>
          <h2 style={styles.h2}>1. Use of the Tool</h2>
          <p style={styles.p}>
            By accessing and utilizing this land calculation application, you explicitly agree to comply with and be bound by the conditions outlined in these Terms of Service. 
            This web utility is provided free of charge for personal, informational, and educational purposes only.
          </p>
        </div>

        <div style={styles.card}>
          <h2 style={styles.cardH2}>2. Accuracy Disclaimer</h2>
          <p style={styles.p}>
            <strong style={{ color: '#fef08a' }}>Important Notice:</strong> While we strive to ensure the structural mathematical accuracy of all conversion modules and equations, 
            land measurements and regional calculation variations (such as Bigha, Guntha, or Marla) can vary significantly across different states, districts, or municipal registry offices. 
            The metrics provided by this platform are close approximations. This calculation script should <strong style={{ color: '#fef08a' }}>not</strong> be used as a binding substitute for professional land surveys, legal real estate deeds, or official government structural measurement paperwork.
          </p>
        </div>

        <div>
          <h2 style={styles.h2}>3. Limitation of Liability</h2>
          <p style={styles.p}>
            Under no circumstances shall the owners, maintainers, or hosting developers of this application be held legally liable for any financial losses, property boundary disputes, 
            or transactional errors resulting from the metrics generated by this calculation tool. Users are highly encouraged to cross-verify all critical land estimations with official local registry frameworks.
          </p>
        </div>
      </section>

      <div style={styles.footerLink}>
        <Link href="/" style={{ color: '#34d399', textDecoration: 'none' }}>
          &larr; Return to Land Calculator Tool
        </Link>
      </div>
    </main>
  );
}
